In [1]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import LogisticRegression
from model.analyze import analyze_variables
from model.train import (
    cross_validation,
    grid_report,
    load_data,
    random_seed,
)
from model.model import save_model
import random

random.seed(random_seed)

In [2]:
train_dataset, test_dataset = load_data("../data/raw_data.csv")
experiment = "adaboost"
case_folder = f"./reports/{experiment}"


def model_path(output_folder: str):
    return f"{output_folder}/model"

In [3]:
output_folder = f"{case_folder}/trees"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
8,13.550304,0.999846,0.635572,0.182235,1.0,200,"{'model__learning_rate': 1, 'model__n_estimato...",0.974030,0.971527,0.974351,0.975602,0.974977,0.974097,0.001394,1
7,7.682385,1.042080,0.587492,0.126963,1.0,100,"{'model__learning_rate': 1, 'model__n_estimato...",0.974030,0.971214,0.974038,0.975602,0.974977,0.973972,0.001502,2
5,15.907184,1.810849,1.055251,0.094212,0.5,200,"{'model__learning_rate': 0.5, 'model__n_estima...",0.970588,0.970275,0.974664,0.975602,0.974977,0.973221,0.002300,3
6,4.443999,0.314834,0.364120,0.070874,1.0,50,"{'model__learning_rate': 1, 'model__n_estimato...",0.972466,0.969962,0.971849,0.973725,0.973100,0.972220,0.001291,4
4,8.623778,1.760614,0.594009,0.073019,0.5,100,"{'model__learning_rate': 0.5, 'model__n_estima...",0.967772,0.964330,0.969033,0.969972,0.968095,0.967841,0.001916,5

In [4]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__learning_rate': 1, 'model__n_estimators': 200}

2025/02/24 07:29:09 INFO mlflow.tracking.fluent: Experiment with name 'adaboost' does not exist. Creating a new experiment.

              precision    recall  f1-score   support

           0     0.9847    0.9958    0.9902      5742
           1     0.9939    0.9776    0.9857      3974

    accuracy                         0.9884      9716
   macro avg     0.9893    0.9867    0.9879      9716
weighted avg     0.9884    0.9884    0.9884      9716

2025/02/24 07:29:15 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.

In [5]:
output_folder = f"{case_folder}/linear"
grid, summary = cross_validation(
    [("model", AdaBoostClassifier())],
    train_dataset,
    {   
        "model__estimator": [LogisticRegression()],
        "model__n_estimators": [50, 100, 200],
        "model__learning_rate": [0.1, 0.5, 1],
    },
    include_all=True,
    include_bias=True,
)
summary

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_model__estimator,param_model__learning_rate,param_model__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
2,30.748541,0.942519,0.804284,0.040110,LogisticRegression(),0.1,200,"{'model__estimator': LogisticRegression(), 'mo...",0.973091,0.969962,0.973413,0.973725,0.974977,0.973034,0.001663,1
1,16.384019,1.280989,0.411680,0.055486,LogisticRegression(),0.1,100,"{'model__estimator': LogisticRegression(), 'mo...",0.972153,0.968398,0.973100,0.973413,0.974664,0.972345,0.002131,2
7,7.482768,2.074852,0.298618,0.042821,LogisticRegression(),1.0,100,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974977,0.972095,0.002901,3
8,6.609331,0.802348,0.221576,0.087299,LogisticRegression(),1.0,200,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974977,0.972095,0.002901,3
6,6.934848,1.163179,0.271670,0.047722,LogisticRegression(),1.0,50,"{'model__estimator': LogisticRegression(), 'mo...",0.969962,0.967459,0.974351,0.973725,0.974038,0.971907,0.002734,5

In [6]:
model = grid_report(grid, test_dataset, experiment)
save_model(model, model_path(output_folder))
analyze_variables(model, test_dataset, output_folder)

{'model__estimator': LogisticRegression(), 'model__learning_rate': 0.1, 'model__n_estimators': 200}
              precision    recall  f1-score   support

           0     0.9843    0.9906    0.9874      5742
           1     0.9863    0.9771    0.9817      3974

    accuracy                         0.9851      9716
   macro avg     0.9853    0.9838    0.9845      9716
weighted avg     0.9851    0.9851    0.9851      9716

2025/02/24 07:31:56 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.